# Generated by Django 3.2.6 on 2021-09-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='numero',
            field=models.IntegerField(blank=True),
        ),
    ]
