# Generated by Django 3.2.6 on 2021-09-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_producto_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
