# Generated by Django 3.2.6 on 2021-09-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
