# Generated by Django 3.2.6 on 2021-09-07 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_producto_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='numero',
            new_name='numero_telefonico',
        ),
    ]
