# Generated by Django 3.2.6 on 2021-09-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_producto_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_Expiracion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_Publicacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
